### ISSUE TITLE
Write for us

### ISSUE THREAD

**Issue by aeliavision** [morpheuslord/Brute-Framework#1]
I'm sorry for writing here but it was the only way to contact you,
Write for us
You are good in the cybersecurity field? Then you can write for us about your own tool on GitHub and the use of it.
Your article will be published with your name and a link to your website and social media accounts if you want.
please reply to this Email:kalitutwrite @ gmail .com
Walid Salame
www. kalitut .com
Twitter: @xKaliSec

**Comment by morpheuslord** [comment]
I would seriously love to promote my tool as I feel it can help ameture
hackers please I will appreciate your help

**Comment by aeliavision** [comment]
Great, please write your article and send it to my email kalitutwrite@gmail .com or you can email me there for help on how to write it perfectly

**Comment by morpheuslord** [comment]
> Great, please write your article and send it to my email kalitutwrite@gmail .com or you can email me there for help on how to write it perfectly

I have written an email please check the email 
And u can email to my other email address 
Morpheuslord@protonmail.com

**Comment by aeliavision** [comment]
i checked the email, i wanted you to write a new article more details and easy tutorial for usage, 
indeed in the email, i see you copied the same github page

**Comment by morpheuslord** [comment]
> i checked the email, i wanted you to write a new article more details and easy tutorial for usage,
> indeed in the email, i see you copied the same github page

Y'a u see I am very bad at explaining stuff so I will edit it and add various tutorials links for all the tools and I will add some Gifs for running all the tools with the Readme copy

**Comment by morpheuslord** [comment]
> i checked the email, i wanted you to write a new article more details and easy tutorial for usage,
> indeed in the email, i see you copied the same github page

I am from India and over here we are having 2nd pu board exams and I have to study for that so I am not able to spend time for programming and updating the tool.

**Comment by morpheuslord** [comment]
> i checked the email, i wanted you to write a new article more details and easy tutorial for usage,
> indeed in the email, i see you copied the same github page

U can add this lines to the article rest all is self explanatory 

usage
It's easy to use to run the tools u need to type :

λ list
In the command interface U will be shown all the tools included by me This command will lead to the main framework

λ Brute-framework 
U need to type this command to access most of the tools If u type this command in the total kit

In brute-framework u can see all the tools included

U will be prompted to this command interface after u type

λ Brute-Framework
U have to type help command in the new interface to see the listed commands

Users[]- help
U can access other tools by checking the user_aliases.cmd file in the config folder u can add and delete tools from it U can take YouTube for learning the nessary skills I prefer these YouTube channel :- *nullbyte *networkchuck *zsecurity.

And for brute framework original code check this channel :- *TechnicalUserX.

Thank u

**Comment by morpheuslord** [comment]
Or u can even check the Readme.md file from the Brute-Hacking-Framework-SourceCode repo that's fully explained in it

**Comment by morpheuslord** [comment]
I have sent you a new mail and I think that much is enough my tool is easy to understand I think so I really don't know
